Repository ekmpa/CrediGraph, pull requests merged in 2025-07, with the labels that each got.

#39 Fluff readme
  README.md
  img/logo.png
  img/logo_gold.png
  img/logo_no_background.png
  img/logo_silver.png
Labels: media

#47 Gnn validation split
  tgrag/dataset/temporal_dataset.py
  tgrag/experiments/gnn_experiment.py
  tgrag/utils/plot.py
Labels: experiments

#49 Logger fix
  configs/gnn_rni/base.yaml
  tgrag/experiments/gnn_experiment.py
  tgrag/experiments/main.py
  tgrag/utils/logger.py
Labels: enhancement

#69 Fix pr
  configs/pr_correlation/base.yaml
  scripts/pr_correlation_experiment.py
  tgrag/experiments/correlation_experiments/main.py
  tgrag/experiments/correlation_experiments/pr_correlation_experiment.py
  tgrag/utils/args.py
  tgrag/utils/path.py
  tgrag/utils/plot.py
Labels: experiments

#90 Graph construction
  bash_scripts/CC-Crawls/CC-2024-nov.txt
  bash_scripts/README.MD
  bash_scripts/end-to-end.sh
  bash_scripts/get_data.sh
  bash_scripts/pipeline.sh
  bash_scripts/run_link_to_graph.sh
  tgrag/construct_graph_scripts/process_compressed_text.py
  tgrag/utils/aggregate.py
  tgrag/utils/data_loading.py
Labels: enhancement, Data, graph representation

#85 fix: removing 100* of results in logger
  configs/gnn_rni/base.yaml
  tgrag/dataset/temporal_dataset.py
  tgrag/encoders/log_encoding.py
  tgrag/experiments/gnn_experiments/gnn_experiment.py
  tgrag/experiments/gnn_experiments/main.py
  tgrag/gnn/GAT.py
  tgrag/gnn/SAGE.py
  tgrag/gnn/gCon.py
  tgrag/utils/data_loading.py
  tgrag/utils/logger.py
  tgrag/utils/plot.py
Labels: bug, experiments, GNN Baseline

#82 script converting txt to csv w/ sqlite, merging ranks/HC
  tgrag/construct_graph_scripts/construct_baseline_dataset.py
  tgrag/construct_graph_scripts/merge_dqr_ratings_trie.py
  tgrag/construct_graph_scripts/merge_dqr_ratings_trie_filter.py
  tgrag/construct_graph_scripts/txt_to_csv_sqlite.py
  tgrag/utils/prob.py
Labels: Data

#93 Re-organize utils
  bash_scripts/pipeline.sh
  test/test_construct/test_article_level.py
  test/test_construct/test_contains_domain.py
  test/test_construct/test_subnetwork_construction.py
  tgrag/construct_graph_scripts/article_merge.py
  tgrag/construct_graph_scripts/construct_aggregate.py
  tgrag/construct_graph_scripts/construct_subnetwork.py
  tgrag/construct_graph_scripts/main.py
  tgrag/construct_graph_scripts/run.sh
  tgrag/construct_graph_scripts/temporal_merge.py
  tgrag/utils/aggregate.py
  tgrag/utils/article_merger.py
  tgrag/utils/data_loading.py
  tgrag/utils/load_labels.py
  tgrag/utils/merger.py
  tgrag/utils/mergers.py
  tgrag/utils/process_compressed_text.py
  tgrag/utils/text_merger.py
Labels: enhancement

#100 Removed experiment logs
  tgrag/experiments/logs/newexp-test-7203340.err
  tgrag/experiments/logs/newexp-test-7203340.out
Labels: invalid

#92 fix: now checking negative ones not na values
  tgrag/construct_graph_scripts/construct_baseline_dataset.py
  tgrag/construct_graph_scripts/merge_dqr_ratings_trie_filter.py
  tgrag/dataset/temporal_dataset.py
  tgrag/encoders/log_encoding.py
  tgrag/experiments/gnn_experiments/gnn_experiment.py
  tgrag/utils/prob.py
Labels: bug

#106 update: making baseline construct script more general
  tgrag/construct_graph_scripts/construct_baseline_dataset.py
Labels: Data

#112 Fix gnn train
  tgrag/experiments/gnn_experiments/gnn_experiment_full_batch.py
Labels: bug

#101 Integration of the PR/HC set in graph construction
  bash_scripts/pipeline.sh
  tgrag/construct_graph_scripts/construct_aggregate.py
  tgrag/utils/data_loading.py
  tgrag/utils/load_labels.py
Labels: Data

#115 Fix train return
  tgrag/experiments/gnn_experiments/gnn_experiment.py
  tgrag/experiments/gnn_experiments/gnn_experiment_full_batch.py
  tgrag/experiments/gnn_experiments/main.py
  tgrag/utils/logger.py
  tgrag/utils/plot.py
Labels: enhancement

#126 Making construction more robust: remove duplicates, ensure all labell…
  tgrag/construct_graph_scripts/construct_aggregate.py
Labels: bug, enhancement

#137 Br gnn bug fixes
  tgrag/dataset/temporal_dataset.py
  tgrag/experiments/gnn_experiments/gnn_experiment.py
  tgrag/experiments/gnn_experiments/gnn_experiment_full_batch.py
  tgrag/utils/plot.py
Labels: bug
